name: Test script on Ubuntu/Debian Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test automated setup
      run: docker build . --file tests/ubuntu/Dockerfile --tag system-setup-ubuntu:$(date +%s) && docker run -t system-setup-ubuntu:$(date +%s)
